### ISSUE TITLE
train_dpm.py: error: unrecognized arguments: --load_pkl True --pkl_path

### ISSUE THREAD

**Issue by lvhualong** [AICPS/sg-collision-prediction#11]
![image](https://user-images.githubusercontent.com/26672004/180595478-1d6cdf8b-df5a-445a-bfa6-fefa93e17879.png)

**Comment by malawada** [comment]
Hello, thanks for pointing out this issue. I fixed the readme to indicate that the proper command argument is --cache_path <pkl file>. Also, it appears you are trying to use a dpm pkl file with train_sg2vec.py. 

If you are trying to train the baseline model (DPM), you should instead use train_dpm.py --cache_path ../dpm_271_carla.pkl. 

If you want to train the sg2vec model, you should instead use the scene graph dataset from here: https://ieee-dataport.org/documents/scenegraph-risk-assessment-dataset. 

Best,

Arnav

**Comment by malawada** [comment]
Also, we have an updated repository with more detailed code for scene-graph extraction and modeling for AVs here:
https://github.com/AICPS/roadscene2vec

**Comment by lvhualong** [comment]
Great job
Thank you for your thoughtful response~
